# Generated by Django 5.0.1 on 2024-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pet_images'),
        ),
    ]
